import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "@/components/shared/Navbar"
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      {/* <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.1.1/flowbite.min.css"  rel="stylesheet" /> */}
      </head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar/>
        <div className='max-w-6xl m-auto px-5'>
          {children}
        </div>
        <script async src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.1.1/flowbite.min.js"></script>
      </body>
    </html>
  )
}
